# Tarea del Jueves, Datos de la OCDE

## ¿Qué haremos?

   - Buscar patrones
   - Buscar relaciones
   - Cosas curiosas de los datos

## ¿Qué usaremos?

   - Usaremos pandas para el análisis
   - Usaremos matplotlib.pyplot para gráficas
   - Usaremos numpy

In [9]:
#Importar las librerías
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
#Importar la base de datos

OCDE=pd.read_csv("BLI.csv")

#OJO: El procedimiento es Importar librerías, cargar BD, limpiar y analizar.

In [13]:
#Cuántos países son y cuáles son

paises=OCDE["Country"].unique()
pd.DataFrame(paises)

                  0
0         Australia
1           Austria
2           Belgium
3            Canada
4    Czech Republic
5           Denmark
6           Finland
7            France
8           Germany
9            Greece
10          Hungary
11          Iceland
12          Ireland
13            Italy
14            Japan
15            Korea
16       Luxembourg
17           Mexico
18      Netherlands
19      New Zealand
20           Norway
21           Poland
22         Portugal
23  Slovak Republic
24            Spain
25           Sweden
26      Switzerland
27           Turkey
28   United Kingdom
29    United States
30           Brazil
31            Chile
32          Estonia
33           Israel
34           Latvia
35           Russia
36         Slovenia
37     South Africa
38     OECD - Total

In [17]:
#Cuántos países
cantidad_paises= len(OCDE["Country"].unique())-1
print("La cantidad de países de la OCDE es: ", cantidad_paises)

La cantidad de países de la OCDE es:  38

In [19]:
#Cuántos tipos de unidades se manejan
tipos_de_unidades= OCDE["Unit"].unique()
pd.DataFrame(tipos_de_unidades)

                            0
0                  Percentage
1               Average score
2                       Ratio
3                   US Dollar
4                       Years
5  Micrograms per cubic metre
6                       Hours

In [22]:
numero_unidades = len(OCDE["Unit"].unique())
print("Las unidades que se manejan son: " ,numero_unidades)

Las unidades que se manejan son:  7

In [24]:
#Indicadores

cantidad_indicadores= len(OCDE["Indicator"].unique())
print("La cantidad de indicadores es: ",cantidad_indicadores)

indicadores=OCDE["Indicator"].unique()
pd.DataFrame(indicadores)

La cantidad de indicadores es:  24

                                                    0
0                            Labour market insecurity
1   Stakeholder engagement for developing regulations
2                 Feeling safe walking alone at night
3                  Dwellings without basic facilities
4                                 Housing expenditure
5                                    Rooms per person
6            Household net adjusted disposable income
7                      Household net financial wealth
8                                     Employment rate
9                         Long-term unemployment rate
10                                  Personal earnings
11                         Quality of support network
12                             Educational attainment
13                                     Student skills
14                                 Years in education
15                                      Air pollution
16                                      Water quality
17                                      Voter turnout
18                                    Life expectancy
19                               Self-reported health
20                                  Life satisfaction
21                                      Homicide rate
22                  Employees working very long hours
23          Time devoted to leisure and personal care

In [25]:
## Dudas de cómo obtener; descripción básica de los indicadores (Estadística descriptiva)
OCDE.describe()

       PowerCode Code  Reference Period Code  Reference Period          Value
count          3398.0                    0.0               0.0    3398.000000
mean              0.0                    NaN               NaN    5353.200309
std               0.0                    NaN               NaN   15832.099269
min               0.0                    NaN               NaN       0.000000
25%               0.0                    NaN               NaN       7.000000
50%               0.0                    NaN               NaN      62.000000
75%               0.0                    NaN               NaN      91.000000
max               0.0                    NaN               NaN  176076.000000

In [73]:
#Después de observar todas las columnas de la BD, decidí eliminar las siguientes:
OCDE_columnas_elim=OCDE.drop(["MEASURE", "INEQUALITY","Unit Code","PowerCode Code","Reference Period Code","Flag Codes","Flags"],axis=1)
pd.DataFrame(OCDE_columnas_elim)

,LOCATION,Country,INDICATOR,Indicator,Measure,Inequality,Unit,PowerCode,Reference Period,Value
0,AUS,Australia,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.30
1,AUT,Austria,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.70
2,BEL,Belgium,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.80
3,CAN,Canada,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,3.90
4,CZE,Czech Republic,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,1.80
5,DNK,Denmark,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.30
6,FIN,Finland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.70
7,FRA,France,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,5.00
8,DEU,Germany,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.00
9,GRC,Greece,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,17.40
10,HUN,Hungary,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.80
11,ISL,Iceland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.60
12,IRL,Ireland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.10
13,ITA,Italy,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,8.10
14,JPN,Japan,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,1.50
15,KOR,Korea,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.40
16,LUX,Luxembourg,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,3.20
17,MEX,Mexico,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.60
18,NLD,Netherlands,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.10
19,NZL,New Zealand,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.90
20,NOR,Norway,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.70
21,POL,Poland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.30
22,PRT,Portugal,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,6.50
23,SVK,Slovak Republic,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,6.70
24,ESP,Spain,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,17.30
25,SWE,Sweden,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,5.70
26,CHE,Switzerland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,1.80
27,TUR,Turkey,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,13.00
28,GBR,United Kingdom,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.60
29,USA,United States,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,3.80
...,...,...,...,...,...,...,...,...,...,...
3368,GRC,Greece,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.42
3369,HUN,Hungary,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.82
3370,ISL,Iceland,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,13.87
3371,IRL,Ireland,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.06
3372,ITA,Italy,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.29
3373,JPN,Japan,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.53
3374,KOR,Korea,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.00
3375,LUX,Luxembourg,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.92
3376,MEX,Mexico,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,12.39
3377,NLD,Netherlands,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.71
3378,NZL,New Zealand,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.95
3379,NOR,Norway,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.65
3380,POL,Poland,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.08
3381,PRT,Portugal,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.64
3382,SVK,Slovak Republic,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.77
3383,ESP,Spain,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.48
3384,SWE,Sweden,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.23
3385,CHE,Switzerland,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.78
3386,TUR,Turkey,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,12.22
3387,GBR,United Kingdom,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.86
3388,USA,United States,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.39
3389,BRA,Brazil,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.18
3390,CHL,Chile,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.66
3391,EST,Estonia,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.43
3392,ISR,Israel,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,13.63
3393,LVA,Latvia,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,13.45
3394,RUS,Russia,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.66
3395,SVN,Slovenia,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.17
3396,ZAF,South Africa,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.37
3397,OECD,OECD - Total,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.60

In [74]:
#Visualizo los encabezados, para poder renombrerlos luego
OCDE_columnas_elim.head()

,LOCATION,Country,INDICATOR,Indicator,Measure,Inequality,Unit,PowerCode,Reference Period,Value
0,AUS,Australia,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.3
1,AUT,Austria,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.7
2,BEL,Belgium,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.8
3,CAN,Canada,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,3.9
4,CZE,Czech Republic,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,1.8

In [76]:
#ahora, cambio los encabezados a idioma español
OCDE_columnas_elim=OCDE_columnas_elim.rename(columns={"LOCATION":"Locación","Country":"País","INDICATOR":"INDICADOR","Indicator":"Significado","Measure":"Medida","Inequality":"Desigualdad","Unit":"Unidad","PowerCode":"Código","Reference Period":"Período Referencia","Value":"Valor"})
OCDE_columnas_elim.head()

,Locación,País,INDICADOR,Significado,Medida,Desigualdad,Unidad,Código,Período Referencia,Valor
0,AUS,Australia,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.3
1,AUT,Austria,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.7
2,BEL,Belgium,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.8
3,CAN,Canada,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,3.9
4,CZE,Czech Republic,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,1.8

In [54]:
#Muevo el índice a que sea LOCATION, luego localizo la info de México
OCDE_2=OCDE.set_index("LOCATION")
OCDE_mx= OCDE_2.loc["MEX"]
pd.DataFrame(OCDE_mx)

,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
LOCATION,,,,,,,,,,,,,,,,
MEX,Mexico,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.60,NaN,NaN
MEX,Mexico,CG_SENG,Stakeholder engagement for developing regulations,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,3.50,NaN,NaN
MEX,Mexico,CG_SENG,Stakeholder engagement for developing regulations,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,3.50,E,Estimated value
MEX,Mexico,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,3.50,E,Estimated value
MEX,Mexico,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,45.90,NaN,NaN
MEX,Mexico,PS_FSAFEN,Feeling safe walking alone at night,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,48.20,NaN,NaN
MEX,Mexico,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,43.60,NaN,NaN
MEX,Mexico,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.20,NaN,NaN
MEX,Mexico,HO_BASE,Dwellings without basic facilities,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,4.20,E,Estimated value
MEX,Mexico,HO_BASE,Dwellings without basic facilities,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,4.20,E,Estimated value
MEX,Mexico,HO_HISH,Housing expenditure,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,21.00,NaN,NaN
MEX,Mexico,HO_HISH,Housing expenditure,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,21.00,E,Estimated value
MEX,Mexico,HO_HISH,Housing expenditure,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,21.00,E,Estimated value
MEX,Mexico,HO_NUMR,Rooms per person,L,Value,TOT,Total,RATIO,Ratio,0,Units,NaN,NaN,1.00,NaN,NaN
MEX,Mexico,HO_NUMR,Rooms per person,L,Value,MN,Men,RATIO,Ratio,0,Units,NaN,NaN,1.00,E,Estimated value
MEX,Mexico,HO_NUMR,Rooms per person,L,Value,WMN,Women,RATIO,Ratio,0,Units,NaN,NaN,1.00,E,Estimated value
MEX,Mexico,IW_HADI,Household net adjusted disposable income,L,Value,TOT,Total,USD,US Dollar,0,Units,NaN,NaN,13891.00,NaN,NaN
MEX,Mexico,IW_HADI,Household net adjusted disposable income,L,Value,MN,Men,USD,US Dollar,0,Units,NaN,NaN,13891.00,E,Estimated value
MEX,Mexico,IW_HADI,Household net adjusted disposable income,L,Value,WMN,Women,USD,US Dollar,0,Units,NaN,NaN,13891.00,E,Estimated value
MEX,Mexico,IW_HADI,Household net adjusted disposable income,L,Value,HGH,High,USD,US Dollar,0,Units,NaN,NaN,35912.00,E,Estimated value
MEX,Mexico,IW_HADI,Household net adjusted disposable income,L,Value,LW,Low,USD,US Dollar,0,Units,NaN,NaN,3444.00,E,Estimated value
MEX,Mexico,IW_HNFW,Household net financial wealth,L,Value,TOT,Total,USD,US Dollar,0,Units,NaN,NaN,4750.00,E,Estimated value
MEX,Mexico,IW_HNFW,Household net financial wealth,L,Value,MN,Men,USD,US Dollar,0,Units,NaN,NaN,4750.00,E,Estimated value
MEX,Mexico,IW_HNFW,Household net financial wealth,L,Value,WMN,Women,USD,US Dollar,0,Units,NaN,NaN,4750.00,E,Estimated value
MEX,Mexico,JE_EMPL,Employment rate,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,61.00,NaN,NaN
MEX,Mexico,JE_EMPL,Employment rate,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,79.00,NaN,NaN
MEX,Mexico,JE_EMPL,Employment rate,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,45.00,NaN,NaN
MEX,Mexico,JE_EMPL,Employment rate,L,Value,HGH,High,PC,Percentage,0,Units,NaN,NaN,80.00,E,Estimated value
MEX,Mexico,JE_EMPL,Employment rate,L,Value,LW,Low,PC,Percentage,0,Units,NaN,NaN,65.00,E,Estimated value
MEX,Mexico,JE_LTUR,Long-term unemployment rate,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,0.08,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MEX,Mexico,EQ_WATER,Water quality,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,67.00,NaN,NaN
MEX,Mexico,EQ_WATER,Water quality,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,66.00,NaN,NaN
MEX,Mexico,EQ_WATER,Water quality,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,68.00,NaN,NaN
MEX,Mexico,CG_VOTO,Voter turnout,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,63.00,NaN,NaN
MEX,Mexico,CG_VOTO,Voter turnout,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
MEX,Mexico,CG_VOTO,Voter turnout,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
MEX,Mexico,CG_VOTO,Voter turnout,L,Value,HGH,High,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
MEX,Mexico,CG_VOTO,Voter turnout,L,Value,LW,Low,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
MEX,Mexico,HS_LEB,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,75.00,NaN,NaN
MEX,Mexico,HS_LEB,Life expectancy,L,Value,MN,Men,YR,Years,0,Units,NaN,NaN,72.30,NaN,NaN
MEX,Mexico,HS_LEB,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,77.70,NaN,NaN
MEX,Mexico,HS_SFRH,Self-reported health,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,66.00,NaN,NaN
MEX,Mexico,HS_SFRH,Self-reported health,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,67.00,NaN,NaN
MEX,Mexico,HS_SFRH,Self-reported health,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,64.00,NaN,NaN
MEX,Mexico,HS_SFRH,Self-reported health,L,Value,HGH,High,PC,Percentage,0,Units,NaN,NaN,78.00,E,Estimated value
MEX,Mexico,HS_SFRH,Self-reported health,L,Value,LW,Low,PC,Percentage,0,Units,NaN,NaN,57.00,E,Estimated value
MEX,Mexico,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.60,NaN,NaN
MEX,Mexico,SW_LIFS,Life satisfaction,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,6.50,NaN,NaN
MEX,Mexico,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,6.60,NaN,NaN
MEX,Mexico,SW_LIFS,Life satisfaction,L,Value,HGH,High,AVSCORE,Average score,0,Units,NaN,NaN,7.40,NaN,NaN
MEX,Mexico,SW_LIFS,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,6.10,NaN,NaN
MEX,Mexico,PS_REPH,Homicide rate,L,Value,TOT,Total,RATIO,Ratio,0,Units,NaN,NaN,17.90,NaN,NaN
MEX,Mexico,PS_REPH,Homicide rate,L,Value,MN,Men,RATIO,Ratio,0,Units,NaN,NaN,33.50,NaN,NaN
MEX,Mexico,PS_REPH,Homicide rate,L,Value,WMN,Women,RATIO,Ratio,0,Units,NaN,NaN,4.20,NaN,NaN
MEX,Mexico,WL_EWLH,Employees working very long hours,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,29.48,NaN,NaN
MEX,Mexico,WL_EWLH,Employees working very long hours,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,36.27,NaN,NaN
MEX,Mexico,WL_EWLH,Employees working very long hours,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,18.39,NaN,NaN
MEX,Mexico,WL_TNOW,Time devoted to leisure and personal care,L,Value,TOT,Total,HOUR,Hours,0,Units,NaN,NaN,12.74,E,Estimated value
MEX,Mexico,WL_TNOW,Time devoted to leisure and personal care,L,Value,MN,Men,HOUR,Hours,0,Units,NaN,NaN,13.03,E,Estimated value
MEX,Mexico,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,12.39,E,Estimated value

In [55]:
#Elimino la columna "Country"
OCDE_sin_country=OCDE_mx.drop(['Country'],axis=1)
pd.DataFrame(OCDE_sin_country)

,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
LOCATION,,,,,,,,,,,,,,,
MEX,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.60,NaN,NaN
MEX,CG_SENG,Stakeholder engagement for developing regulations,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,3.50,NaN,NaN
MEX,CG_SENG,Stakeholder engagement for developing regulations,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,3.50,E,Estimated value
MEX,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,3.50,E,Estimated value
MEX,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,45.90,NaN,NaN
MEX,PS_FSAFEN,Feeling safe walking alone at night,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,48.20,NaN,NaN
MEX,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,43.60,NaN,NaN
MEX,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.20,NaN,NaN
MEX,HO_BASE,Dwellings without basic facilities,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,4.20,E,Estimated value
MEX,HO_BASE,Dwellings without basic facilities,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,4.20,E,Estimated value
MEX,HO_HISH,Housing expenditure,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,21.00,NaN,NaN
MEX,HO_HISH,Housing expenditure,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,21.00,E,Estimated value
MEX,HO_HISH,Housing expenditure,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,21.00,E,Estimated value
MEX,HO_NUMR,Rooms per person,L,Value,TOT,Total,RATIO,Ratio,0,Units,NaN,NaN,1.00,NaN,NaN
MEX,HO_NUMR,Rooms per person,L,Value,MN,Men,RATIO,Ratio,0,Units,NaN,NaN,1.00,E,Estimated value
MEX,HO_NUMR,Rooms per person,L,Value,WMN,Women,RATIO,Ratio,0,Units,NaN,NaN,1.00,E,Estimated value
MEX,IW_HADI,Household net adjusted disposable income,L,Value,TOT,Total,USD,US Dollar,0,Units,NaN,NaN,13891.00,NaN,NaN
MEX,IW_HADI,Household net adjusted disposable income,L,Value,MN,Men,USD,US Dollar,0,Units,NaN,NaN,13891.00,E,Estimated value
MEX,IW_HADI,Household net adjusted disposable income,L,Value,WMN,Women,USD,US Dollar,0,Units,NaN,NaN,13891.00,E,Estimated value
MEX,IW_HADI,Household net adjusted disposable income,L,Value,HGH,High,USD,US Dollar,0,Units,NaN,NaN,35912.00,E,Estimated value
MEX,IW_HADI,Household net adjusted disposable income,L,Value,LW,Low,USD,US Dollar,0,Units,NaN,NaN,3444.00,E,Estimated value
MEX,IW_HNFW,Household net financial wealth,L,Value,TOT,Total,USD,US Dollar,0,Units,NaN,NaN,4750.00,E,Estimated value
MEX,IW_HNFW,Household net financial wealth,L,Value,MN,Men,USD,US Dollar,0,Units,NaN,NaN,4750.00,E,Estimated value
MEX,IW_HNFW,Household net financial wealth,L,Value,WMN,Women,USD,US Dollar,0,Units,NaN,NaN,4750.00,E,Estimated value
MEX,JE_EMPL,Employment rate,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,61.00,NaN,NaN
MEX,JE_EMPL,Employment rate,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,79.00,NaN,NaN
MEX,JE_EMPL,Employment rate,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,45.00,NaN,NaN
MEX,JE_EMPL,Employment rate,L,Value,HGH,High,PC,Percentage,0,Units,NaN,NaN,80.00,E,Estimated value
MEX,JE_EMPL,Employment rate,L,Value,LW,Low,PC,Percentage,0,Units,NaN,NaN,65.00,E,Estimated value
MEX,JE_LTUR,Long-term unemployment rate,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,0.08,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MEX,EQ_WATER,Water quality,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,67.00,NaN,NaN
MEX,EQ_WATER,Water quality,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,66.00,NaN,NaN
MEX,EQ_WATER,Water quality,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,68.00,NaN,NaN
MEX,CG_VOTO,Voter turnout,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,63.00,NaN,NaN
MEX,CG_VOTO,Voter turnout,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
MEX,CG_VOTO,Voter turnout,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
MEX,CG_VOTO,Voter turnout,L,Value,HGH,High,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
MEX,CG_VOTO,Voter turnout,L,Value,LW,Low,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
MEX,HS_LEB,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,75.00,NaN,NaN
MEX,HS_LEB,Life expectancy,L,Value,MN,Men,YR,Years,0,Units,NaN,NaN,72.30,NaN,NaN
MEX,HS_LEB,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,77.70,NaN,NaN
MEX,HS_SFRH,Self-reported health,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,66.00,NaN,NaN
MEX,HS_SFRH,Self-reported health,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,67.00,NaN,NaN
MEX,HS_SFRH,Self-reported health,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,64.00,NaN,NaN
MEX,HS_SFRH,Self-reported health,L,Value,HGH,High,PC,Percentage,0,Units,NaN,NaN,78.00,E,Estimated value
MEX,HS_SFRH,Self-reported health,L,Value,LW,Low,PC,Percentage,0,Units,NaN,NaN,57.00,E,Estimated value
MEX,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.60,NaN,NaN
MEX,SW_LIFS,Life satisfaction,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,6.50,NaN,NaN
MEX,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,6.60,NaN,NaN
MEX,SW_LIFS,Life satisfaction,L,Value,HGH,High,AVSCORE,Average score,0,Units,NaN,NaN,7.40,NaN,NaN
MEX,SW_LIFS,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,6.10,NaN,NaN
MEX,PS_REPH,Homicide rate,L,Value,TOT,Total,RATIO,Ratio,0,Units,NaN,NaN,17.90,NaN,NaN
MEX,PS_REPH,Homicide rate,L,Value,MN,Men,RATIO,Ratio,0,Units,NaN,NaN,33.50,NaN,NaN
MEX,PS_REPH,Homicide rate,L,Value,WMN,Women,RATIO,Ratio,0,Units,NaN,NaN,4.20,NaN,NaN
MEX,WL_EWLH,Employees working very long hours,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,29.48,NaN,NaN
MEX,WL_EWLH,Employees working very long hours,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,36.27,NaN,NaN
MEX,WL_EWLH,Employees working very long hours,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,18.39,NaN,NaN
MEX,WL_TNOW,Time devoted to leisure and personal care,L,Value,TOT,Total,HOUR,Hours,0,Units,NaN,NaN,12.74,E,Estimated value
MEX,WL_TNOW,Time devoted to leisure and personal care,L,Value,MN,Men,HOUR,Hours,0,Units,NaN,NaN,13.03,E,Estimated value
MEX,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,12.39,E,Estimated value

# Muestra los países con esperanza de vida femenina mayor al promedio general y sus datos

In [57]:
OCDE_vida=OCDE.set_index("INDICATOR")
expectativa = OCDE_vida.loc["HS_LEB"]
pd.DataFrame(expectativa)

,LOCATION,Country,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
INDICATOR,,,,,,,,,,,,,,,,
HS_LEB,AUS,Australia,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.5,NaN,NaN
HS_LEB,AUT,Austria,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.3,NaN,NaN
HS_LEB,BEL,Belgium,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.1,NaN,NaN
HS_LEB,CAN,Canada,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.5,NaN,NaN
HS_LEB,CZE,Czech Republic,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,78.7,NaN,NaN
HS_LEB,DNK,Denmark,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,80.8,NaN,NaN
HS_LEB,FIN,Finland,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.6,NaN,NaN
HS_LEB,FRA,France,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.4,NaN,NaN
HS_LEB,DEU,Germany,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,80.7,NaN,NaN
HS_LEB,GRC,Greece,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.1,NaN,NaN
HS_LEB,HUN,Hungary,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,75.7,NaN,NaN
HS_LEB,ISL,Iceland,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.5,NaN,NaN
HS_LEB,IRL,Ireland,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.5,NaN,NaN
HS_LEB,ITA,Italy,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.6,NaN,NaN
HS_LEB,JPN,Japan,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,83.9,NaN,NaN
HS_LEB,KOR,Korea,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.1,NaN,NaN
HS_LEB,LUX,Luxembourg,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.4,NaN,NaN
HS_LEB,MEX,Mexico,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,75.0,NaN,NaN
HS_LEB,NLD,Netherlands,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.6,NaN,NaN
HS_LEB,NZL,New Zealand,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.7,NaN,NaN
HS_LEB,NOR,Norway,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.4,NaN,NaN
HS_LEB,POL,Poland,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,77.6,NaN,NaN
HS_LEB,PRT,Portugal,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.2,NaN,NaN
HS_LEB,SVK,Slovak Republic,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,76.7,NaN,NaN
HS_LEB,ESP,Spain,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,83.0,NaN,NaN
HS_LEB,SWE,Sweden,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.3,NaN,NaN
HS_LEB,CHE,Switzerland,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,83.0,NaN,NaN
HS_LEB,TUR,Turkey,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,78.0,NaN,NaN
HS_LEB,GBR,United Kingdom,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.0,NaN,NaN
HS_LEB,USA,United States,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,78.8,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
HS_LEB,GRC,Greece,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,83.7,NaN,NaN
HS_LEB,HUN,Hungary,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,79.0,NaN,NaN
HS_LEB,ISL,Iceland,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,83.8,NaN,NaN
HS_LEB,IRL,Ireland,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,83.4,NaN,NaN
HS_LEB,ITA,Italy,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,84.9,NaN,NaN
HS_LEB,JPN,Japan,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,87.1,NaN,NaN
HS_LEB,KOR,Korea,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,85.2,NaN,NaN
HS_LEB,LUX,Luxembourg,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,84.7,NaN,NaN
HS_LEB,MEX,Mexico,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,77.7,NaN,NaN
HS_LEB,NLD,Netherlands,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,83.2,NaN,NaN
HS_LEB,NZL,New Zealand,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,83.4,NaN,NaN
HS_LEB,NOR,Norway,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,84.2,NaN,NaN
HS_LEB,POL,Poland,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,81.6,NaN,NaN
HS_LEB,PRT,Portugal,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,84.3,NaN,NaN
HS_LEB,SVK,Slovak Republic,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,80.2,NaN,NaN
HS_LEB,ESP,Spain,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,85.8,NaN,NaN
HS_LEB,SWE,Sweden,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,84.1,NaN,NaN
HS_LEB,CHE,Switzerland,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,85.1,NaN,NaN
HS_LEB,TUR,Turkey,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,80.7,NaN,NaN
HS_LEB,GBR,United Kingdom,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,82.8,NaN,NaN
HS_LEB,USA,United States,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,81.2,NaN,NaN
HS_LEB,BRA,Brazil,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,78.5,NaN,NaN
HS_LEB,CHL,Chile,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,81.7,NaN,NaN
HS_LEB,EST,Estonia,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,82.2,NaN,NaN
HS_LEB,ISR,Israel,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,84.1,NaN,NaN
HS_LEB,LVA,Latvia,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,79.5,NaN,NaN
HS_LEB,RUS,Russia,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,76.7,NaN,NaN
HS_LEB,SVN,Slovenia,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,83.9,NaN,NaN
HS_LEB,ZAF,South Africa,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,59.5,NaN,NaN
HS_LEB,OECD,OECD - Total,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,82.7,NaN,NaN

In [58]:
expectativa=expectativa.set_index('Inequality')

In [65]:
mujeres_expectativa=expectativa.loc['Women']

In [68]:
mujeres_expectativa.describe()

       PowerCode Code  Reference Period Code  Reference Period      Value
count            39.0                    0.0               0.0  39.000000
mean              0.0                    NaN               NaN  82.241026
std               0.0                    NaN               NaN   4.378880
min               0.0                    NaN               NaN  59.500000
25%               0.0                    NaN               NaN  81.600000
50%               0.0                    NaN               NaN  83.400000
75%               0.0                    NaN               NaN  84.250000
max               0.0                    NaN               NaN  87.100000

In [72]:
valores_mujer = mujeres_expectativa['Value']
## Pregunta cuáles países tienen expectativa de vida mayor al promedio

#Parámetro de filtro = ['Value']restricción
promedio_vida=82.24
total=valores_mujer.count()

P_V = sum(valores_mujer>promedio_vida)
p_promedio = P_V/total

print("Existen ", P_V, " países con expectativa mayor al promedio", "de un total de ", total)
print("Esto representa el ", round(p_promedio,4)*100, "% del total de la muestra, según un parámetro promedio_vida= ",promedio_vida)

Existen  26  países con expectativa mayor al promedio de un total de  39
Esto representa el  66.67 % del total de la muestra, según un parámetro promedio_vida=  82.24

In [83]:
#Para conocer cuáles países son los de mejor esperanza de vida (arriba del promedio)
#mujeres_expectativa=mujeres_expectativa.drop(["MEASURE", "INEQUALITY","Unit Code","PowerCode Code","Reference Period Code","Flag Codes","Flags"],axis=1)
Expectativa_arriba_media = mujeres_expectativa[mujeres_expectativa['Value'] > 82.24 ]
#Puedo acomodar el set de datos, de mayor a menor expectativa... 
Expectativa_arriba_sorteada=Expectativa_arriba_media.sort_values(by=['Value'],axis=0,ascending=False)
pd.DataFrame(Expectativa_arriba_sorteada)

,LOCATION,Country,Indicator,Measure,Unit,PowerCode,Reference Period,Value
Inequality,,,,,,,,
Women,JPN,Japan,Life expectancy,Value,Years,Units,NaN,87.1
Women,ESP,Spain,Life expectancy,Value,Years,Units,NaN,85.8
Women,FRA,France,Life expectancy,Value,Years,Units,NaN,85.5
Women,KOR,Korea,Life expectancy,Value,Years,Units,NaN,85.2
Women,CHE,Switzerland,Life expectancy,Value,Years,Units,NaN,85.1
Women,ITA,Italy,Life expectancy,Value,Years,Units,NaN,84.9
Women,LUX,Luxembourg,Life expectancy,Value,Years,Units,NaN,84.7
Women,AUS,Australia,Life expectancy,Value,Years,Units,NaN,84.5
Women,FIN,Finland,Life expectancy,Value,Years,Units,NaN,84.4
Women,PRT,Portugal,Life expectancy,Value,Years,Units,NaN,84.3
Women,NOR,Norway,Life expectancy,Value,Years,Units,NaN,84.2
Women,ISR,Israel,Life expectancy,Value,Years,Units,NaN,84.1
Women,SWE,Sweden,Life expectancy,Value,Years,Units,NaN,84.1
Women,SVN,Slovenia,Life expectancy,Value,Years,Units,NaN,83.9
Women,ISL,Iceland,Life expectancy,Value,Years,Units,NaN,83.8
Women,GRC,Greece,Life expectancy,Value,Years,Units,NaN,83.7
Women,AUT,Austria,Life expectancy,Value,Years,Units,NaN,83.7
Women,CAN,Canada,Life expectancy,Value,Years,Units,NaN,83.6
Women,NZL,New Zealand,Life expectancy,Value,Years,Units,NaN,83.4
Women,BEL,Belgium,Life expectancy,Value,Years,Units,NaN,83.4
Women,IRL,Ireland,Life expectancy,Value,Years,Units,NaN,83.4
Women,NLD,Netherlands,Life expectancy,Value,Years,Units,NaN,83.2
Women,DEU,Germany,Life expectancy,Value,Years,Units,NaN,83.1
Women,GBR,United Kingdom,Life expectancy,Value,Years,Units,NaN,82.8
Women,DNK,Denmark,Life expectancy,Value,Years,Units,NaN,82.7
Women,OECD,OECD - Total,Life expectancy,Value,Years,Units,NaN,82.7

# Muestra los países cuya seguridad al caminar por la noche es menor al promedio general y sus datos

In [84]:
# Primero, debo crear un DataSet nuevo, para comenzar a trabajar
Seguridad_Noche= OCDE
#quito las columnas extra
Seguridad_Noche=Seguridad_Noche.drop(["MEASURE", "INEQUALITY","Unit Code","PowerCode Code","Reference Period Code","Flag Codes","Flags"],axis=1)

In [90]:
#Ahora, filtro con base al indicador 'Feeling safe walking alone at night'
Seguridad_Noche=Seguridad_Noche[Seguridad_Noche['Indicator'] =='Feeling safe walking alone at night'] 
Seguridad_Noche=Seguridad_Noche[Seguridad_Noche['Inequality'] =='Total']
pd.DataFrame(Seguridad_Noche)

,LOCATION,Country,INDICATOR,Indicator,Measure,Inequality,Unit,PowerCode,Reference Period,Value
154,AUS,Australia,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,63.6
155,AUT,Austria,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,80.7
156,BEL,Belgium,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,70.7
157,CAN,Canada,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,80.9
158,CZE,Czech Republic,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,68.3
159,DNK,Denmark,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,83.0
160,FIN,Finland,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,82.9
161,FRA,France,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,69.6
162,DEU,Germany,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,75.9
163,GRC,Greece,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,61.8
164,HUN,Hungary,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,50.7
165,ISL,Iceland,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,87.0
166,IRL,Ireland,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,75.5
167,ITA,Italy,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,58.3
168,JPN,Japan,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,70.6
169,KOR,Korea,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,63.9
170,LUX,Luxembourg,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,72.0
171,MEX,Mexico,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,45.9
172,NLD,Netherlands,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,81.2
173,NZL,New Zealand,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,64.8
174,NOR,Norway,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,87.7
175,POL,Poland,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,66.3
176,PRT,Portugal,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,72.1
177,SVK,Slovak Republic,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,60.1
178,ESP,Spain,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,83.1
179,SWE,Sweden,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,75.9
180,CHE,Switzerland,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,84.0
181,TUR,Turkey,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,60.6
182,GBR,United Kingdom,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,77.4
183,USA,United States,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,74.1
184,BRA,Brazil,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,37.3
185,CHL,Chile,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,51.1
186,EST,Estonia,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,67.2
187,ISR,Israel,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,70.2
188,LVA,Latvia,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,60.7
189,RUS,Russia,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,52.2
190,SVN,Slovenia,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,84.7
191,ZAF,South Africa,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,36.1
192,OECD,OECD - Total,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,68.6

In [91]:
#Observo las estadísticas de este indicador, con el fin de  conocer el promedio.
Seguridad_Noche.describe()

       Reference Period      Value
count               0.0  39.000000
mean                NaN  68.633333
std                 NaN  13.020860
min                 NaN  36.100000
25%                 NaN  61.250000
50%                 NaN  70.200000
75%                 NaN  79.050000
max                 NaN  87.700000

In [92]:
#Creo un DataSet filtrado, donde aparezcan solamente los paises que se encuentran por debajo del promedio del indicador 
#'Feeling safe walking alone at night'
Inseguros_Noche=Seguridad_Noche[Seguridad_Noche['Value']<68.63333]
print("Países cuya seguridad al caminar en la noche es menor al promedio y su información")
Inseguros_Noche.sort_values(by=['Value'],axis=0,ascending=False)

Países cuya seguridad al caminar en la noche es menor al promedio y su información

,LOCATION,Country,INDICATOR,Indicator,Measure,Inequality,Unit,PowerCode,Reference Period,Value
192,OECD,OECD - Total,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,68.6
158,CZE,Czech Republic,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,68.3
186,EST,Estonia,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,67.2
175,POL,Poland,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,66.3
173,NZL,New Zealand,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,64.8
169,KOR,Korea,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,63.9
154,AUS,Australia,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,63.6
163,GRC,Greece,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,61.8
188,LVA,Latvia,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,60.7
181,TUR,Turkey,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,60.6
177,SVK,Slovak Republic,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,60.1
167,ITA,Italy,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,58.3
189,RUS,Russia,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,52.2
185,CHL,Chile,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,51.1
164,HUN,Hungary,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,50.7
171,MEX,Mexico,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,45.9
184,BRA,Brazil,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,37.3
191,ZAF,South Africa,PS_FSAFEN,Feeling safe walking alone at night,Value,Total,Percentage,Units,NaN,36.1


# Muestra las columnas de los datos completos de los países con mejor satisfacción de vida

In [93]:
#Genero otro DataSet con el indicador que me solicitan, 
Satisfac_Vida=OCDE[OCDE['Indicator'] =='Life satisfaction'] 
#Discrimino solamente los totales (recordar que hay tres indicadores por cada medición)
Satisfac_Vida=Satisfac_Vida[Satisfac_Vida['Inequality'] =='Total']
#Ordeno el DataSet de mayor calidad de vida a menor
Satisfac_Vida.sort_values(by=['Value'],axis=0,ascending=False)

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
2870,ISL,Iceland,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
2885,CHE,Switzerland,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
2879,NOR,Norway,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
2864,DNK,Denmark,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
2865,FIN,Finland,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
2877,NLD,Netherlands,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.4,NaN,NaN
2859,AUS,Australia,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.3,NaN,NaN
2884,SWE,Sweden,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.3,NaN,NaN
2878,NZL,New Zealand,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.3,NaN,NaN
2862,CAN,Canada,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.3,NaN,NaN
2892,ISR,Israel,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.2,NaN,NaN
2867,DEU,Germany,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.0,NaN,NaN
2871,IRL,Ireland,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.0,NaN,NaN
2860,AUT,Austria,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.0,NaN,NaN
2875,LUX,Luxembourg,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.9,NaN,NaN
2888,USA,United States,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.9,NaN,NaN
2861,BEL,Belgium,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.9,NaN,NaN
2890,CHL,Chile,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.7,NaN,NaN
2887,GBR,United Kingdom,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.7,NaN,NaN
2889,BRA,Brazil,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.6,NaN,NaN
2876,MEX,Mexico,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.6,NaN,NaN
2863,CZE,Czech Republic,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.6,NaN,NaN
2897,OECD,OECD - Total,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.5,NaN,NaN
2883,ESP,Spain,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.4,NaN,NaN
2866,FRA,France,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.4,NaN,NaN
2882,SVK,Slovak Republic,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.1,NaN,NaN
2880,POL,Poland,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.0,NaN,NaN
2894,RUS,Russia,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.0,NaN,NaN
2874,KOR,Korea,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.9,NaN,NaN
2873,JPN,Japan,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.9,NaN,NaN
2872,ITA,Italy,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.9,NaN,NaN
2893,LVA,Latvia,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.9,NaN,NaN
2895,SVN,Slovenia,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.8,NaN,NaN
2891,EST,Estonia,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.6,NaN,NaN
2886,TUR,Turkey,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.5,NaN,NaN
2869,HUN,Hungary,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.3,NaN,NaN
2881,PRT,Portugal,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.2,NaN,NaN
2868,GRC,Greece,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.2,NaN,NaN
2896,ZAF,South Africa,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,4.8,NaN,NaN

In [94]:
#quito las columnas extra
Satisfac_Vida=Satisfac_Vida.drop(["MEASURE", "INEQUALITY","Unit Code","PowerCode Code","Reference Period Code","Flag Codes","Flags"],axis=1)

In [96]:
pd.DataFrame(Satisfac_Vida)

,LOCATION,Country,INDICATOR,Indicator,Measure,Inequality,Unit,PowerCode,Reference Period,Value
2859,AUS,Australia,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,7.3
2860,AUT,Austria,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,7.0
2861,BEL,Belgium,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,6.9
2862,CAN,Canada,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,7.3
2863,CZE,Czech Republic,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,6.6
2864,DNK,Denmark,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,7.5
2865,FIN,Finland,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,7.5
2866,FRA,France,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,6.4
2867,DEU,Germany,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,7.0
2868,GRC,Greece,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,5.2
2869,HUN,Hungary,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,5.3
2870,ISL,Iceland,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,7.5
2871,IRL,Ireland,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,7.0
2872,ITA,Italy,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,5.9
2873,JPN,Japan,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,5.9
2874,KOR,Korea,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,5.9
2875,LUX,Luxembourg,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,6.9
2876,MEX,Mexico,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,6.6
2877,NLD,Netherlands,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,7.4
2878,NZL,New Zealand,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,7.3
2879,NOR,Norway,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,7.5
2880,POL,Poland,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,6.0
2881,PRT,Portugal,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,5.2
2882,SVK,Slovak Republic,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,6.1
2883,ESP,Spain,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,6.4
2884,SWE,Sweden,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,7.3
2885,CHE,Switzerland,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,7.5
2886,TUR,Turkey,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,5.5
2887,GBR,United Kingdom,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,6.7
2888,USA,United States,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,6.9
2889,BRA,Brazil,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,6.6
2890,CHL,Chile,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,6.7
2891,EST,Estonia,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,5.6
2892,ISR,Israel,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,7.2
2893,LVA,Latvia,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,5.9
2894,RUS,Russia,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,6.0
2895,SVN,Slovenia,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,5.8
2896,ZAF,South Africa,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,4.8
2897,OECD,OECD - Total,SW_LIFS,Life satisfaction,Value,Total,Average score,Units,NaN,6.5

In [95]:
Satisfac_Vida.describe()

       Reference Period      Value
count               0.0  39.000000
mean                NaN   6.528205
std                 NaN   0.766039
min                 NaN   4.800000
25%                 NaN   5.900000
50%                 NaN   6.600000
75%                 NaN   7.250000
max                 NaN   7.500000